# Generated by Django 5.0.6 on 2024-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Kazakhstan News', 'Новости Казахстана'), ('Mangystau News', 'Новости Мангистау'), ('World News', 'Мировые новости'), ('President', 'Президент'), ('Meetings', 'Встречи'), ('Economy', 'Экономика'), ('Sport', 'Спорт'), ('Ecology', 'Экология'), ('Medicine', 'Медицина'), ('Education', 'Образование'), ('Culture', 'Культура'), ('True', 'Правда'), ('Youth', 'Молодежь')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('News', 'Новости'), ('Policy', 'Политика'), ('Society', 'Общество'), ('Advertising', 'Реклама'), ('By hearing', 'На слуху')], max_length=20),
        ),
    ]
