# Generated by Django 5.0.6 on 2024-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_exclusive_news_subcategory_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
