# Generated by Django 5.0.6 on 2024-10-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('News', 'Новости'), ('Policy', 'Политика'), ('Society', 'Общество'), ('Advertising', 'Реклама'), ('By hearing', 'На слуху'), ('Analytics', 'Аналитика'), ('People from Mangystau', 'Выходцы из Мангыстау')], max_length=50),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
