# Generated by Django 5.0.6 on 2025-02-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_link_to_source_alter_newsimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('News', 'Новости'), ('Policy', 'Политика'), ('Society', 'Общество'), ('Advertising', 'Реклама'), ('By hearing', 'На слуху'), ('Compliance', 'СОГЛАСИЕ'), ('Analytics', 'Аналитика'), ('People from Mangystau', 'Выходцы из Мангыстау')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='link_to_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news_files/'),
        ),
        migrations.CreateModel(
            name='NewsCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='news.news')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
