# Generated by Django 5.0.6 on 2025-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_announcement_alter_news_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('NEWS_RENT', 'Новости аренды'), ('NEWS_LEGAL', 'Новости юриспруденции'), ('NEWS_HR', 'Новости HR'), ('NEWS_ACCOUNTING', 'Новости бухгалтерии'), ('NEWS_HOLIDAY', 'Новости праздников'), ('PARTNERS', 'Партнеры')], max_length=50),
        ),
    ]
