# Generated by Django 5.0.6 on 2025-06-18 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('aho', 'АХО')], default='aho', max_length=50)),
                ('type', models.CharField(choices=[('stationery', 'Выдача канцелярских товаров'), ('workspace', 'Организация рабочего места'), ('procurement', 'Приобретение ТРУ'), ('travel_expense', 'Возмещение командировочных расходов'), ('cartridge', 'Запрос картриджей'), ('components', 'Комплектующие и расходные материалы')], max_length=50)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='requests/')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подписи'), ('signed', 'Подписана'), ('under_review', 'На рассмотрении'), ('approved', 'Одобрена модератором'), ('assigned', 'Назначена исполнителю'), ('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_requests', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_requests', to=settings.AUTH_USER_MODEL)),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ASCFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ADM/')),
                ('ASC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ADM.request')),
            ],
        ),
        migrations.CreateModel(
            name='ASCCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='ADM/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('ASC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='ADM.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ADM.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='ADM.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
