# Generated by Django 5.0.6 on 2025-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='related_user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
