# Generated by Django 5.0.6 on 2025-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADM', '0003_city_region_requestcategory_request_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
    ]
