# Generated by Django 5.0.6 on 2025-06-28 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADM', '0004_remove_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('categories', models.ManyToManyField(related_name='user_groups', to='ADM.requestcategory')),
                ('cities', models.ManyToManyField(related_name='user_groups', to='ADM.city')),
                ('regions', models.ManyToManyField(related_name='user_groups', to='ADM.region')),
                ('users', models.ManyToManyField(related_name='groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
