# Generated by Django 5.0.6 on 2025-06-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADM', '0005_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='moderator',
        ),
        migrations.AddField(
            model_name='request',
            name='moderator_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ADM.usergroup'),
        ),
    ]
