# Generated by Django 5.0.6 on 2025-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADM', '0006_remove_request_moderator_request_moderator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
