# Generated by Django 5.0.6 on 2025-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_department_organization_position_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, unique=True),
        ),
    ]
