# Generated by Django 5.0.6 on 2025-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_department_parent_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер әкімші'), ('guest', 'Гость'), ('moderator', 'Модератор'), ('executor', 'исполнитель')], default='guest', max_length=20),
        ),
    ]
