# Generated by Django 5.0.6 on 2025-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('law', 'Юридическая база'), ('accounting', 'Бухгалтерская база')], max_length=20)),
                ('file', models.FileField(upload_to='knowledge_base/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
